import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Urbanist,
  Source_Serif_4,
  Cedarville_Cursive,
  Instrument_Serif,
  Schibsted_Grotesk,
  Fustat,
  Noto_Sans,
  Manrope,
  Cabin,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  weight: ["600", "700"],
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const sourceSerif4 = Source_Serif_4({
  weight: ["400", "600"],
  variable: "--font-source-serif-4",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const cedarvilleCursive = Cedarville_Cursive({
  weight: "400",
  variable: "--font-cedarville-cursive",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  weight: ["400"],
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const schibstedGrotesk = Schibsted_Grotesk({
  weight: ["400", "500", "600", "700"],
  variable: "--font-schibsted-grotesk",
  subsets: ["latin"],
});

const fustat = Fustat({
  weight: ["400", "500", "600", "700"],
  variable: "--font-fustat",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const manrope = Manrope({
  weight: ["400", "500", "600", "700"],
  variable: "--font-manrope",
  subsets: ["latin"],
});

const cabin = Cabin({
  weight: ["400", "500", "600", "700"],
  variable: "--font-cabin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${urbanist.variable} ${sourceSerif4.variable} ${cedarvilleCursive.variable} ${instrumentSerif.variable} ${schibstedGrotesk.variable} ${fustat.variable} ${notoSans.variable} ${manrope.variable} ${cabin.variable} h-full antialiased`}
    >
      <head>
        <link
          href="https://db.onlinewebfonts.com/c/04e6981992c0e2e7642af2074ebe3901?family=Helvetica+Now+Display+Bold"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}